#!/usr/bin/env bash
set -euo pipefail

source config

# /etc/apt/apt.conf.d/70debconf sets
# DPkg::Pre-Install-Pkgs {"/usr/sbin/dpkg-preconfigure --apt || true";};
# which pre-configures all packages. We do not want that when building
# the container, hence zap the file.
rm /etc/apt/apt.conf.d/70debconf

apt-get update
