#!/usr/bin/env bash
set -euo pipefail

source config

readarray DEFAULT_PACKAGES <<EOF
asymptote
biber
build-essential
cwebx
debhelper
dh-python
doxygen
g++
gcc
gcovr
git
imagemagick
lcov
python3
python3-click
python3-dev
python3-libtmux
python3-pexpect
python3-pip
python3-prompt-toolkit
python3-psutil
python3-pyelftools
python3-pygments
python3-pytest
python3-wheel
python3-xdg
r-cran-knitr
rubber
texinfo
tmux
transfig
EOF
apt-get ${APT_INSTALL} ${DEFAULT_PACKAGES[@]}

readarray PACKAGES_WITH_RECOMMENDS <<EOF
texlive-full
EOF
apt-get -y install ${PACKAGES_WITH_RECOMMENDS[@]}

readarray REMOVE_PACKAGES <<EOF
texlive-fonts-extra-doc
texlive-fonts-recommended-doc
texlive-humanities-doc
texlive-latex-base-doc
texlive-latex-extra-doc
texlive-latex-recommended-doc
texlive-metapost-doc
texlive-pictures-doc
texlive-pstricks-doc
texlive-publishers-doc
texlive-science-doc
EOF

apt-get remove -y ${REMOVE_PACKAGES[@]}
