#!/usr/bin/env bash
set -euo pipefail

source config

readarray DEFAULT_PACKAGES <<EOF
asymptote
bc
biber
build-essential
ccache
cmake
cppcheck
curl
cwebx
debhelper
dh-python
doxygen
g++
gcc
gcovr
git
gnupg2
golang
graphviz
imagemagick
lcov
libargon2-dev
libboost-all-dev
libfmt-dev
libgomp1
libgtest-dev
libsodium-dev
libtbb-dev
libtbb2
liburcu-dev
liburing-dev
linux-perf
lsb-release
nasm
ninja-build
openjdk-17-jdk-headless
openssh-client
parallel
pkg-config
pyflakes3
pylint
python3
python3-click
python3-dev
python3-libtmux
python3-matplotlib
python3-numpy
python3-pexpect
python3-pip
python3-prompt-toolkit
python3-psutil
python3-pyelftools
python3-pyflakes
python3-pygments
python3-pytest
python3-wheel
python3-xdg
r-cran-knitr
ripgrep
rubber
sudo
tarlz
texinfo
tmux
transfig
tree
valgrind
wget
EOF
apt-get ${APT_INSTALL} ${DEFAULT_PACKAGES[@]}

readarray PACKAGES_WITH_RECOMMENDS <<EOF
texlive-full
EOF
apt-get -y install ${PACKAGES_WITH_RECOMMENDS[@]}

readarray REMOVE_PACKAGES <<EOF
texlive-fonts-extra-doc
texlive-fonts-recommended-doc
texlive-humanities-doc
texlive-latex-base-doc
texlive-latex-extra-doc
texlive-latex-recommended-doc
texlive-metapost-doc
texlive-pictures-doc
texlive-pstricks-doc
texlive-publishers-doc
texlive-science-doc
EOF

dpkg -r --force-depends ${REMOVE_PACKAGES[@]}

apt-get autoremove -y -f
