#!/usr/bin/env bash
set -euo pipefail
set -x

source config

readonly LLVM_VERSIONS=(
    13
)

install_llvm() {
    local llvm_version="${1}"

    local debian_codename
    debian_codename=$(lsb_release --codename --short)

    local llvm_repo_name
    local llvm_repo_dir
    case "${debian_codename}" in
	bookworm)
	    llvm_repo_name="llvm-toolchain-${llvm_version}"
	    llvm_repo_dir="unstable"
	    ;;
	*)
	    llvm_repo_name="llvm-toolchain-${debian_codename}-${llvm_version}"
	    llvm_repo_dir="${debian_codename}"
	    ;;
    esac

    cat <<EOF > /etc/apt/sources.list.d/llvm-${llvm_version}.list
deb http://apt.llvm.org/${llvm_repo_dir}/ ${llvm_repo_name} main
deb-src http://apt.llvm.org/${llvm_repo_dir}/ ${llvm_repo_name} main
EOF

    apt-get update

    readarray LLVM_PACKAGES <<EOF
clang-${LLVM_VERSION}
clang-format-${LLVM_VERSION}
clang-tidy-${LLVM_VERSION}
clang-tools-${LLVM_VERSION}
clangd-${LLVM_VERSION}
libc++-${LLVM_VERSION}-dev
libc++1-${LLVM_VERSION}
libc++abi-${LLVM_VERSION}-dev
libc++abi1-${LLVM_VERSION}
libclang-${LLVM_VERSION}-dev
libclang-common-${LLVM_VERSION}-dev
libclang1-${LLVM_VERSION}
libclc-${LLVM_VERSION}
libfuzzer-${LLVM_VERSION}-dev
libllvm-${LLVM_VERSION}-ocaml-dev
libllvm${LLVM_VERSION}
libomp-${LLVM_VERSION}-dev
lld-${LLVM_VERSION}
lldb-${LLVM_VERSION}
llvm-${LLVM_VERSION}
llvm-${LLVM_VERSION}-dev
llvm-${LLVM_VERSION}-examples
llvm-${LLVM_VERSION}-runtime
python3-clang-${LLVM_VERSION}
EOF

    apt-get ${APT_INSTALL} ${LLVM_PACKAGES[@]}

    if [[ "${llvm_version}" == "${LLVM_VERSIONS[-1]}" ]]; then
	# Make libomp findable via e.g. Meson's find_library()
	ln -s "/usr/lib/llvm-${llvm_version}/lib/libomp.so" /usr/lib
    fi
}

curl https://apt.llvm.org/llvm-snapshot.gpg.key --output /etc/apt/trusted.gpg.d/llvm-snapshot.asc

for LLVM_VERSION in "${LLVM_VERSIONS[@]}"; do
    install_llvm "${LLVM_VERSION}"
done
