#!/usr/bin/env bash
set -euo pipefail

source config

cat <<EOF > /etc/apt/sources.list.d/llvm.list
deb http://apt.llvm.org/bullseye/ llvm-toolchain-bullseye-12 main
deb-src http://apt.llvm.org/bullseye/ llvm-toolchain-bullseye-12 main
EOF

wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | apt-key add -

apt-get update

readarray LLVM_PACKAGES <<EOF
clang-12
clang-format-12
clang-tidy-12
clang-tools-12
clangd-12
libc++-12-dev
libc++abi-12-dev
libclang-12-dev
libclang-common-12-dev
libclang1-12
libclc-12
libfuzzer-12-dev
libllvm-12-ocaml-dev
libllvm12
libomp-12-dev
lld-12
lldb-12
llvm-12
llvm-12-dev
llvm-12-examples
llvm-12-runtime
python3-clang-12
EOF

apt-get ${APT_INSTALL} ${LLVM_PACKAGES[@]}
