#!/usr/bin/env bash
set -euo pipefail

source config

cat <<EOF > /etc/apt/sources.list.d/llvm.list
deb http://apt.llvm.org/bullseye/ llvm-toolchain-bullseye-12 main
deb-src http://apt.llvm.org/bullseye/ llvm-toolchain-bullseye-12 main
EOF

wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | apt-key add -

apt-get update

readarray LLVM_PACKAGES <<EOF
clang-12
clang-format-12
clang-tidy-12
clang-tools-12
libclang-12-dev
llvm-12
llvm-12-dev
EOF

apt-get ${APT_INSTALL} ${LLVM_PACKAGES[@]}
