#!/usr/bin/env bash
set -euo pipefail

declare -A PIP_PACKAGES=(
	[mypy]=0.910
	[pdoc3]=0.10.0
	[yapf]=0.31.0
	[meson]=0.60.0
)

for pip_package in "${!PIP_PACKAGES[@]}"; do
	pip install ${pip_package}==${PIP_PACKAGES[${pip_package}]}
done
