#!/usr/bin/env bash
set -euo pipefail

declare -A PIP_PACKAGES=(
	[mypy]=0.812
	[pdoc3]=0.9.2
	[yapf]=0.31.0
	[meson]=0.58.0
)

for pip_package in "${!PIP_PACKAGES[@]}"; do
	pip install ${pip_package}==${PIP_PACKAGES[${pip_package}]}
done
