#!/usr/bin/env bash
set -euo pipefail

readonly IWYU_VERSION="0.19"

mkdir iwyu
cd iwyu

readonly IWYU_TAR_GZ_URL="https://include-what-you-use.org/downloads/include-what-you-use-${IWYU_VERSION}.src.tar.gz"

wget "${IWYU_TAR_GZ_URL}"

IWYU_TAR_GZ=$(basename "${IWYU_TAR_GZ_URL}")

tar -xzf "${IWYU_TAR_GZ}"

pushd include-what-you-use

mkdir build
cd build
cmake \
	-DCMAKE_PREFIX_PATH=/usr/lib/llvm-15 \
	..
make -l `nproc` -j `nproc`
make install

popd

cd ../..
rm -rf iwyu
