#!/usr/bin/env bash
set -euo pipefail

readonly MILL_VERSION="0.9.9"

curl -L "https://github.com/com-lihaoyi/mill/releases/download/${MILL_VERSION}/${MILL_VERSION}-assembly" \
     > /usr/local/bin/mill
chmod +x /usr/local/bin/mill
