#!/usr/bin/env bash
set -euo pipefail

readonly AMM_VERSION="2.3.8"
readonly SCALA_VERSION="2.13"

curl -L "https://github.com/com-lihaoyi/Ammonite/releases/download/${AMM_VERSION}/${SCALA_VERSION}-${AMM_VERSION}" \
     > /usr/local/bin/amm
chmod +x /usr/local/bin/amm
