#!/usr/bin/env bash
set -euo pipefail

declare -A PIP_PACKAGES=(
	[mypy]=1.4.1
	[pdoc3]=0.10.0
	[yapf]=0.40.1
	[meson]=1.2.0
)

for pip_package in "${!PIP_PACKAGES[@]}"; do
	pip install \
		--break-system-packages \
		${pip_package}==${PIP_PACKAGES[${pip_package}]}
done
