#!/usr/bin/env bash
set -euo pipefail

declare -A PIP_PACKAGES=(
	[mypy]=0.982
	[pdoc3]=0.10.0
	[yapf]=0.32.0
	[meson]=0.62.2
)

for pip_package in "${!PIP_PACKAGES[@]}"; do
	pip install ${pip_package}==${PIP_PACKAGES[${pip_package}]}
done
