#!/usr/bin/env bash
set -euo pipefail

readonly LLVM_MAJOR_VERSION=14

CLANG_TOOLS=()
CLANG_TOOLS+=(clang)
CLANG_TOOLS+=(clang++)
CLANG_TOOLS+=(clang-format)
CLANG_TOOLS+=(clang-tidy)
CLANG_TOOLS+=(run-clang-tidy)
for CLANG_TOOL in "${CLANG_TOOLS[@]}"; do
	ln "/usr/bin/${CLANG_TOOL}-${LLVM_MAJOR_VERSION}" "/usr/bin/${CLANG_TOOL}"
done

ln /usr/bin/pyflakes3 /usr/bin/pyflakes
ln /usr/bin/python3 /usr/bin/python
