#!/usr/bin/env bash
set -euo pipefail

APT_INSTALL="install -y --no-install-recommends"
export DEBIAN_FRONTEND="noninteractive"

readonly GCC_MAJOR_VERSION="12"

readonly LLVM_VERSION="14.0.6"
declare -ir LLVM_MAJOR_VERSION=$(cut -d. -f1 <<< "${LLVM_VERSION}")
