#!/usr/bin/env bash
set -euo pipefail

APT_INSTALL="install -y --no-install-recommends"
DEBIAN_TESTING_CODENAME="bullseye"
export DEBIAN_FRONTEND="noninteractive"

cat <<EOF > /etc/apt/sources.list.d/testing.list
deb     http://ftp.de.debian.org/debian/    ${DEBIAN_TESTING_CODENAME} main
deb-src http://ftp.de.debian.org/debian/    ${DEBIAN_TESTING_CODENAME} main
EOF

cat <<EOF > /etc/apt/apt.conf.d/default-release-stable
APT::Default-Release "stable";
EOF

apt update

readarray DEFAULT_PACKAGES <<EOF
asymptote
biber
build-essential
clang
clang-tidy
cwebx
debhelper
dh-python
doxygen
g++
gcc
gcovr
imagemagick
iwyu
lcov
libgtest-dev
pyflakes3
python3
python3-click
python3-libtmux
python3-pexpect
python3-pip
python3-prompt-toolkit
python3-psutil
python3-pyelftools
python3-pygments
python3-pytest
python3-xdg
r-cran-knitr
texlive-bibtex-extra
texlive-binaries
texlive-extra-utils
texlive-latex-base
texlive-latex-extra
texlive-latex-recommended
texlive-metapost
texlive-omega
texlive-pictures
tmux
transfig
EOF
apt ${APT_INSTALL} ${DEFAULT_PACKAGES[@]}

readarray BACKPORTS_PACKAGES <<EOF
meson
EOF
apt ${APT_INSTALL} -t buster-backports ${BACKPORTS_PACKAGES[@]}

readarray TESTING_PACKAGES <<EOF
clang-format-10
pylint
EOF
apt ${APT_INSTALL} -t ${DEBIAN_TESTING_CODENAME} ${TESTING_PACKAGES[@]}

pip3 install yapf==0.29.0
pip3 install mypy==0.760
pip3 install pdoc3==0.8.1

ln /usr/bin/clang-format-10 /usr/bin/clang-format
ln /usr/bin/iwyu_tool /usr/bin/iwyu_tool.py
ln /usr/bin/pytest-3 /usr/bin/pytest
ln /usr/bin/pyflakes3 /usr/bin/pyflakes
