#!/usr/bin/env bash
set -euo pipefail

APT_INSTALL="install -y --no-install-recommends"
DEBIAN_TESTING_CODENAME="bullseye"
export DEBIAN_FRONTEND="noninteractive"

cat <<EOF > /etc/apt/sources.list.d/testing.list
deb     http://ftp.de.debian.org/debian/    ${DEBIAN_TESTING_CODENAME} main
deb-src http://ftp.de.debian.org/debian/    ${DEBIAN_TESTING_CODENAME} main
EOF

apt update -qq

DEFAULT_PACKAGES=()
DEFAULT_PACKAGES+=(build-essential)
DEFAULT_PACKAGES+=(clang)
DEFAULT_PACKAGES+=(clang-tidy)
DEFAULT_PACKAGES+=(gcc)
DEFAULT_PACKAGES+=(gcovr)
DEFAULT_PACKAGES+=(g++)
DEFAULT_PACKAGES+=(iwyu)
DEFAULT_PACKAGES+=(lcov)
DEFAULT_PACKAGES+=(libgtest-dev)
apt ${APT_INSTALL} ${DEFAULT_PACKAGES[@]}

BACKPORTS_PACKAGES=()
BACKPORTS_PACKAGES+=(meson)
apt ${APT_INSTALL} -t buster-backports ${BACKPORTS_PACKAGES[@]}

TESTING_PACKAGES=()
TESTING_PACKAGES+=(clang-format-10)
apt ${APT_INSTALL} -t ${DEBIAN_TESTING_CODENAME} ${TESTING_PACKAGES[@]}

ln /usr/bin/clang-format-10 /usr/bin/clang-format
ln /usr/bin/iwyu_tool /usr/bin/iwyu_tool.py
